# Generated by Django 4.0.5 on 2023-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=2)),
                ('attendance', models.CharField(max_length=1)),
            ],
        ),
    ]
