# Generated by Django 4.0.5 on 2023-05-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='day',
        ),
    ]
